import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en: {
        profile: "Profile",
        your_personal_data: "Your personal data",
        your_personal_data_name: "Name",
        your_personal_data_surname: "Surname",
        your_personal_data_email: "Email",
        your_personal_data_password: "Password",
        your_personal_data_confirm_password: "Confirm Password",
        your_personal_data_n_token: "Number of Tokens",
        edit: "Edit",
        save: "Save",
        your_translations: "Your Translations",
        your_translations_status_column: "Status",
        status_approved: "Approved",
        status_discarded: "Discarded",
        status_validation: "Being validated",
        status_in_progress: "In Progress",
        status_approved_and_discarded: "Approved and Discarded",
        your_languages: "Your languages",
        languages: "Languages",
        add: "Add",
        remove: "Remove",
        your_languages_language_column: "Language",
        your_languages_code_column: "Language Code",
        your_languages_remove_column: "Remove",
        logout: "Logout",
        agree: "I Agree",

        select_empty_field: "Choose...",
        restaurant_name: "Restaurant Name",
        restaurant_address: "Address",
        restaurant_city: "City",
        restaurant_language_in_which_translate_menu: "Language in which translate menu",
        restaurant_menu_id: "Menu Id",
        province: "Province",
        restaurant: "Restaurant",
        search: "Search",

        text: "Text",
        translation_language: "Translation Language",
        translated_text: "Translated Text",
        no_elements_prensent_in_the_table: "No elements present in the table",
        submit: "Submit",
        translation_in_progress: "Translation in progress",
        translation_to_review: "Translation to review",
        approve: "Approve",
        discard: "Discard",
        translations: "Translations",
        home: "Home",
        city: "City",
        name: "Name",
        address: "Address",
        street_number: "Street Number",
        add_restaurant: "Add Restaurant",
        add_menu: "Add menu",
        menus: "Menus",
        menu: "Menu",
        title: "Title",
        subtitle: "Subtitle",
        add_section: "Add Section",
        description: "Description",
        section_name: "Section Name",
        dish: "Dish",
        section: "Section",
        add_dish: "Add Dish",
        save_menu: "Save Menu",
        dish_name: "Dish Name",
        price: "Price",
        forgot_password: "Forgot Passoword?",
        wrong_credentials: "Wrong Credentials",
        server_error_communication: "Error Server Communication",
        login: "Login",
        register: "Register",
        go_back: "Back",
        choose_the_user: "Choose the user",
        translator: "Translator",
        restaurateur: "Restaurateur",
        client: "Client",
        compile_all_fields: "Compile all fields",
        the_two_passwords_are_not_equal: "The two password does not match",
        check_i_agree_to_continue: "Check I Agree to continue",
        compile_the_form_to_regiter_as_translator: "Compile the form to register as Translator: ",
        compile_the_form_to_regiter_as_restaurateur: "Compile the form to register as Restaurateur: ",
        email_edited: "Email Changed",
        verify_otp: "Verify OTP",
        request: "Request",
        email_sent: "Email sent to the specified address",
        error_while_editing_email: "Error while editing email",
        the_code_inserted_is_not_correctd: "The code inserted is not corrected",
        verify: "Verify",
        insert_the_otp_code: "Insert the OTP code"

    },
    it: {
        profile: "Profilo",
        your_personal_data: "I tuoi dati personali",
        your_personal_data_name: "Nome",
        your_personal_data_surname: "Cognome",
        your_personal_data_email: "Email",
        your_personal_data_password: "Password",
        your_personal_data_confirm_password: "Conferma Password",
        your_personal_data_n_token: "Numero di Token",
        edit: "Modifica",
        save: "Salva",
        your_translations: "Le tue traduzioni",
        your_translations_status_column: "Stato",
        status_approved: "Approvata",
        status_discarded: "Scartata",
        status_validation: "In fase di convalida",
        status_in_progress: "In corso",
        status_approved_and_discarded: "Approvata e Scartata",
        your_languages: "Le tue lingue",
        languages: "Lingue",
        add: "Aggiungi",
        remove: "Rimuovi",
        your_languages_language_column: "Lingua",
        your_languages_code_column: "Codice Lingua",
        your_languages_remove_column: "Rimuovi",
        logout: "Logout",
        agree: "Accetto",

        select_empty_field: "Scegli...",
        restaurant_name: "Nome Ristorante",
        restaurant_address: "Indirizzo",
        restaurant_city: "Citta",
        restaurant_language_in_which_translate_menu: "Lingua in cui tradurre il menù",
        restaurant_menu_id: "Id menù",
        province: "Provincia",
        restaurant: "Ristorante",
        search: "Cerca",

        text: "Testo",
        translation_language: "Lingua di traduzione",
        translated_text: "Testo tradotto",
        no_elements_prensent_in_the_table: "Nessun elemento presente nella tabella",
        submit: "Invia",
        translation_in_progress: "Traduzioni in corso",
        translation_to_review: "Traduzioni da revisionare",
        approve: "Approva",
        discard: "Scarta",
        translations: "Traduzioni",
        home: "Home",
        city: "Citta",
        name: "Nome",
        address: "Inrizzo",
        street_number: "Civico",
        add_restaurant: "Aggiungi Ristorante",
        add_menu: "Aggiungi Menù",
        menus: "Menù",
        menu: "Menù",
        title: "Titolo",
        subtitle: "Sottotitolo",
        add_section: "Aggiungi Sezione",
        description: "Descrizione",
        section_name: "Nome Sezione",
        dish: "Piatto",
        section: "Sezione",
        add_dish: "Aggiungi Piatto",
        save_menu: "Salva Menù",
        dish_name: "Nome Piatto",
        price: "Prezzo",
        forgot_password: "Dimenticato la password?",
        wrong_credentials: "Credenziali Sbagliate",
        server_error_communication: "Errore di comunicazione con il server",
        login: "Login",
        register: "Registrati",
        go_back: "Indietro",
        choose_the_user: "Scegli l'utente",
        translator: "Traduttore",
        restaurateur: "Ristoratore",
        client: "Cliente",
        compile_all_fields: "Compila tutti i campi",
        the_two_passwords_are_not_equal: "Le due password non coincidono",
        check_i_agree_to_continue: "Spuntare Accetto per proseguire",
        compile_the_form_to_regiter_as_translator: "Compila il form per registrarti come Traduttore: ",
        compile_the_form_to_regiter_as_restaurateur: "Compila il form per registrarti come Ristoratore: ",
        email_edited: "Email Modificata",
        verify_otp: "Verifica OTP",
        request: "Richiedi",
        email_sent: "Email inviata all'indirizzo email specificato",
        error_while_editing_email: "Errore durante la modifica dell'email",
        the_code_inserted_is_not_correctd: "Il codice inserito non è corretto",
        verify: "Verifica",
        insert_the_otp_code: "Inserisci il codice OTP"
    }
});